site_name: Lepsta Documentation
nav:
  - Home: index.md
  - How Lepsta works: pages/lepsta/how-lepsta-works.md
  - Getting started:
    - Installation: pages/installation.md
  - Quick start:
    - Your first repository: pages/quick-start/your-first-repository.md
  - Guides:
    - Create a branch: pages/guides/create-a-branch.md
  - Uju:
    - What is Uju?: pages/uju/what-is-uju.md
  - Known issues:
    - Uju is not running: pages/issues/uju-is-not-running.md
  - Changelog:
    - Changelog: pages/changelog
theme:
  name: material
  custom_dir: overrides
  features:
    - tabs
  palette:
    scheme: preference
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_lepsta
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true